version: "2"

linters:
  default: none
  enable:
    # defaults
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # additional linters
    - exhaustive
    - nonamedreturns
    - predeclared

formatters:
  enable:
    - gofmt

linters-settings:
  govet:
    check-shadowing: true
  staticcheck:
    go: "1.21"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
