# this is copied over from goreleaser/goreleaser/.github/workflows/lint.yml
name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read

jobs:
  golangci:
    permissions:
      contents: read
      pull-requests: read
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.19.5'
          # See https://chat.openai.com/share/588cab85-27f5-4378-8eeb-5700221e5614
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          args: --timeout=5m